name: personal_finance_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  bloc_test: ^10.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
